Make both parameters required to avoid exceptions
Exceptions would otherwise look something like the following:

java.lang.IllegalArgumentException: No implementation of method: :plus- of protocol: #'clj-time.core/DateTimeProtocol found for cl
ass: nil

java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:454)